In [1]:
from bs4 import BeautifulSoup
import re

In [2]:
import pandas as pd
import numpy as np

### Read/Check CSVs Made Below (optional)

In [3]:
Final_CSV = pd.read_csv("../data/FF_MeanImp_Merged_icpICU_PeriodicVitals_WithAtLeast30ButLessThan33001Measurements.csv")
Final_CSV

FileNotFoundError: [Errno 2] No such file or directory: '../data/FF_MeanImp_Merged_icpICU_PeriodicVitals_WithAtLeast30ButLessThan33001Measurements.csv'

In [ ]:
stop here

SyntaxError: invalid syntax (4067800170.py, line 1)

### Start from Here - Make Merged Sheet

In [1]:
import pandas as pd
import numpy as np

In [2]:
st123 = pd.read_csv("../data/Apache4aResults_st123ICUstays_eICUcrd.csv")

In [3]:
st123

,patientunitstayid,apachepatientresultsid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,apacheversion,predictedicumortality,actualicumortality,predictediculos,...,predictedhospitallos,actualhospitallos,preopmi,preopcardiaccath,ptcawithin24h,unabridgedunitlos,unabridgedhosplos,actualventdays,predventdays,unabridgedactualventdays
0,143941,138210,surgery-cardiac,I,53,66,IVa,0.009647,ALIVE,3.273827,...,11.636347,8.0368,0,0,0,5.1222,8.0368,1.0,1.466298,1.0
1,161093,32928,cardiology,Unknown,15,31,IVa,0.006655,ALIVE,1.614840,...,4.960427,9.0910,0,0,0,3.9270,9.0910,NaN,NaN,NaN
2,166995,49211,Specialty Not Specified,Unknown,99,104,IVa,0.352023,ALIVE,8.138206,...,13.947793,2.6028,0,0,0,2.5986,2.6028,3.0,5.276482,3.0
3,177460,65643,pulmonary/CCM,Unknown,12,28,IVa,0.007867,ALIVE,2.363287,...,-1.000000,31.9111,0,0,0,30.6847,31.9111,NaN,NaN,NaN
4,191266,2628,critical care medicine (CCM),Unknown,136,141,IVa,-1.000000,EXPIRED,-1.000000,...,-1.000000,3.5819,0,0,0,3.1298,3.5819,3.0,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,3352114,3245998,cardiology,II,32,48,IVa,0.004637,ALIVE,2.125659,...,9.002716,11.1625,0,0,0,1.0291,11.1625,1.0,1.291392,1.0
1006,3352178,3246014,cardiology,II,32,43,IVa,0.001943,ALIVE,1.371603,...,9.024754,17.0472,0,0,0,1.0611,17.0472,1.0,0.986118,1.0
1007,3352344,3288734,cardiology,II,37,50,IVa,0.001500,ALIVE,1.674129,...,9.313944,44.1444,0,0,0,1.2236,44.1444,1.0,1.070631,1.0
1008,3352620,3267381,cardiology,II,41,58,IVa,0.067335,ALIVE,4.338286,...,9.482292,10.3556,0,0,0,5.3541,10.3556,NaN,NaN,NaN
1009,3352878,3251472,surgery-cardiac,II,65,76,IVa,0.014945,ALIVE,3.779740,...,10.711552,10.5757,0,0,0,3.7708,10.5757,2.0,2.209628,2.0

In [4]:
st123_patientunitstayid = st123[['patientunitstayid']] #.astype('category')
st123_patientunitstayid = st123_patientunitstayid.drop_duplicates().reset_index(drop=True)
st123_patientunitstayid

      patientunitstayid
0                143941
1                161093
2                166995
3                177460
4                191266
...                 ...
1005            3352114
1006            3352178
1007            3352344
1008            3352620
1009            3352878

[1010 rows x 1 columns]


st123_patientunitstayid_series = pd.Series(st123_patientunitstayid['patientunitstayid'].values, dtype='string')
st123_patientunitstayid_series

In [5]:
Cleaned_ApacheResultsSheet = pd.read_csv('../data/EDA_SnapShot_Cleaned_ApacheResultsSheet.csv')

In [6]:
Cleaned_ApacheResultsSheet

,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,predictedicumortality,actualicumortality,predictediculos,actualiculos,predictedhospitalmortality,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
0,141168,critical care medicine (CCM),Unknown,49.0,65.0,0.028889,True,3.091127,2.4972,0.059099,...,9.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
1,141194,critical care medicine (CCM),Unknown,57.0,70.0,0.046448,False,4.167129,3.3423,0.102283,...,4.0,1,NaN,False,4.0,6.0,3.0,NaN,NaN,False
2,141203,hospitalist,I,73.0,90.0,0.291609,False,8.670299,1.2979,0.470973,...,4.0,1,NaN,False,1.0,3.0,1.0,51.0,100.0,False
3,141208,hospitalist,I,17.0,17.0,0.001330,False,0.444563,0.5000,0.002249,...,7.0,1,NaN,False,5.0,6.0,3.0,NaN,NaN,False
4,141227,internal medicine,Unknown,83.0,100.0,0.335934,False,8.209624,1.1472,0.488562,...,6.0,1,NaN,False,4.0,6.0,3.0,65.0,21.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148527,3353235,cardiology,II,30.0,35.0,0.011009,False,1.934817,0.7423,0.022630,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148528,3353237,pulmonary/CCM,II,37.0,54.0,0.026984,False,2.566297,0.8812,0.062568,...,4.0,1,NaN,False,4.0,6.0,4.0,NaN,NaN,False
148529,3353251,cardiology,II,142.0,158.0,0.876797,False,8.920949,11.2909,0.918169,...,8.0,1,NaN,False,1.0,1.0,1.0,80.0,100.0,True
148530,3353254,hospitalist,II,18.0,35.0,0.011004,False,2.045046,0.2993,0.025801,...,4.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148531,3353263,nephrology,II,22.0,22.0,0.006508,False,1.754389,0.6444,0.012324,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False

In [7]:
PeriodicVitals = pd.read_csv("../data/vitalPeriodic_eICUcrd.csv")

Cleaned_ApacheResultsSheet_st123 = Cleaned_ApacheResultsSheet[(Cleaned_ApacheResultsSheet['patientunitstayid'] isin st123_patientunitstayid['patientunitstayid'])] 
Cleaned_ApacheResultsSheet_st123

In [8]:
Merged_cleanedApacheResults_st123patientunitstayid = pd.merge(Cleaned_ApacheResultsSheet, st123_patientunitstayid, on=['patientunitstayid'], how='inner').sort_values(by=['patientunitstayid']) #.drop(columns=['vitalperiodicid', 'etco2', 'icp'])
Merged_cleanedApacheResults_st123patientunitstayid

,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,predictedicumortality,actualicumortality,predictediculos,actualiculos,predictedhospitalmortality,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
0,143941,surgery-cardiac,I,53.0,66.0,0.009647,False,3.273827,5.1222,0.026106,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
1,161093,cardiology,Unknown,15.0,31.0,0.006655,False,1.614840,3.9270,0.018020,...,4.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
2,166995,Specialty Not Specified,Unknown,99.0,104.0,0.352023,False,8.138206,2.5986,0.420008,...,4.0,1,NaN,False,5.0,6.0,4.0,113.0,100.0,False
3,177460,pulmonary/CCM,Unknown,12.0,28.0,0.007867,False,2.363287,30.6847,NaN,...,8.0,2,6.0,False,5.0,6.0,4.0,NaN,NaN,False
4,191266,critical care medicine (CCM),Unknown,136.0,141.0,NaN,True,NaN,3.1298,NaN,...,9.0,1,NaN,False,1.0,1.0,1.0,77.0,60.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,3352114,cardiology,II,32.0,48.0,0.004637,False,2.125659,1.0291,0.012105,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
1006,3352178,cardiology,II,32.0,43.0,0.001943,False,1.371603,1.0611,0.007926,...,8.0,1,NaN,False,5.0,6.0,4.0,158.0,100.0,False
1007,3352344,cardiology,II,37.0,50.0,0.001500,False,1.674129,1.2236,0.010220,...,8.0,1,NaN,False,5.0,6.0,4.0,318.0,100.0,False
1008,3352620,cardiology,II,41.0,58.0,0.067335,False,4.338286,5.3541,0.126773,...,8.0,1,NaN,False,5.0,6.0,4.0,95.0,21.0,False
1009,3352878,surgery-cardiac,II,65.0,76.0,0.014945,False,3.779740,3.7708,0.019591,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False

In [9]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements = pd.merge(PeriodicVitals, st123_patientunitstayid, on=['patientunitstayid'], how='inner').sort_values(by=['patientunitstayid', 'observationoffset']).drop(columns=['vitalperiodicid', 'etco2', 'icp'])
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements.to_csv("../data/Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements.csv", index=False)

In [10]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
650,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
126,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
742,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
622,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
286,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152300,3352878,5401,NaN,99.0,66.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,80.0,0.0
1152340,3352878,5406,NaN,100.0,65.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152364,3352878,5411,NaN,99.0,66.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152428,3352878,5416,NaN,NaN,67.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,90.0,0.0
1152468,3352878,5421,NaN,NaN,68.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.00,80.0,0.0

In [11]:
Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements = pd.merge(PeriodicVitals, Merged_cleanedApacheResults_st123patientunitstayid, on=['patientunitstayid'], how='inner').sort_values(by=['patientunitstayid', 'observationoffset']).drop(columns=['vitalperiodicid', 'etco2', 'icp'])
Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
650,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
126,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
742,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
622,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
286,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152300,3352878,5401,NaN,99.0,66.0,21.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152340,3352878,5406,NaN,100.0,65.0,17.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152364,3352878,5411,NaN,99.0,66.0,18.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152428,3352878,5416,NaN,NaN,67.0,22.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152468,3352878,5421,NaN,NaN,68.0,22.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False

In [12]:
Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1152913 entries, 650 to 1152468
Data columns (total 78 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   patientunitstayid              1152913 non-null  int64
 1   observationoffset              1152913 non-null  int64
 2   temperature                    374731 non-null   float64
 3   sao2                           1056425 non-null  float64
 4   heartrate                      1149754 non-null  float64
 5   respiration                    994367 non-null   float64
 6   cvp                            543200 non-null   float64
 7   systemicsystolic               690767 non-null   float64
 8   systemicdiastolic              690764 non-null   float64
 9   systemicmean                   694743 non-null   float64
 10  pasystolic                     467193 non-null   float64
 11  padiastolic                    467120 non-null   float64
 12  pamean                         470308 non-null   float64
 13  st1                            938151 non-null   float64
 14  st2                            948085 non-null   float64
 15  st3                            937375 non-null   float64
 16  physicianspeciality            1152913 non-null  object
 17  physicianinterventioncategory  1152913 non-null  object
 18  acutephysiologyscore           1129593 non-null  float64
 19  apachescore                    1129593 non-null  float64
 20  predictedicumortality          1094895 non-null  float64
 21  actualicumortality             1152913 non-null  bool
 22  predictediculos                1094895 non-null  float64
 23  actualiculos                   1152913 non-null  float64
 24  predictedhospitalmortality     979937 non-null   float64
 25  actualhospitalmortality        1152913 non-null  bool
 26  predictedhospitallos           979937 non-null   float64
 27  actualhospitallos              1152913 non-null  float64
 28  preopmi                        1152913 non-null  bool
 29  preopcardiaccath               1152913 non-null  bool
 30  ptcawithin24h                  1152913 non-null  bool
 31  unabridgedunitlos              1152913 non-null  float64
 32  unabridgedhosplos              1152913 non-null  float64
 33  actualventdays                 951629 non-null   float64
 34  predventdays                   911039 non-null   float64
 35  unabridgedactualventdays       951629 non-null   float64
 36  gender                         1152913 non-null  object
 37  bedcount                       1152913 non-null  int64
 38  admitsource                    1148946 non-null  float64
 39  graftcount                     1152913 non-null  int64
 40  meds                           1152913 non-null  bool
 41  verbal-gcs                     1107447 non-null  float64
 42  motor-gcs                      1107447 non-null  float64
 43  eyes-gcs                       1107447 non-null  float64
 44  age                            1150095 non-null  float64
 45  admitdiagnosis                 1151414 non-null  object
 46  thrombolytics                  1152913 non-null  bool
 47  diedinhospital                 1152913 non-null  bool
 48  aids                           1152913 non-null  bool
 49  hepaticfailure                 1152913 non-null  bool
 50  lymphoma                       1152913 non-null  bool
 51  metastaticcancer               1152913 non-null  bool
 52  leukemia                       1152913 non-null  bool
 53  immunosuppression              1152913 non-null  bool
 54  cirrhosis                      1152913 non-null  bool
 55  electivesurgery                1152913 non-null  bool
 56  activetx                       1152913 non-null  bool
 57  readmit                        1152913 non-null  bool
 58  ima                            1152913 non-null  bool
 59  midur                          1152913 non-null  bool
 60  ventday1                       1152913 non-null  bool
 61  oobventday1                    1152913 non-null  bool
 62  oobintubday1                   1152913 non-null  bool
 63  diabetes                       1152913 non-null  bool
 64  pao2                           431002 non-null   float64
 65  fio2                           431002 non-null   float64
 66  ejectfx                        223566 non-null   float64
 67  creatinine                     1111675 non-null  float64
 68  dischargelocation              1152913 non-null  float64
 69  visitnumber                    1152913 non-null  int64
 70  amilocation                    57030 non-null    float64
 71  day1meds                       1152913 non-null  bool
 72  day1verbal-gcs                 1107447 non-null  float64
 73  day1motor-gcs                  1107447 non-null  float64
 74  day1eyes-gcs                   1107447 non-null  float64
 75  day1pao2                       431002 non-null   float64
 76  day1fio2                       431002 non-null   float64
 77  PredictedICUmortality_binary   1152913 non-null  bool
dtypes: bool(26), float64(43), int64(5), object(4)
memory usage: 494.8+ MB

In [13]:

Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements.to_csv("../data/Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements.csv", index=False)

In [14]:
Merged_st123ICUstaysPeriodicVitals_cleanedApacheResults_WithAtLeast30ButLessThan33001Measurements.tail(99)

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
1152737,3352878,4931,NaN,97.0,74.0,25.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152581,3352878,4936,NaN,97.0,75.0,23.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152683,3352878,4941,NaN,96.0,75.0,21.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152773,3352878,4946,NaN,96.0,77.0,21.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152602,3352878,4951,NaN,95.0,76.0,25.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152300,3352878,5401,NaN,99.0,66.0,21.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152340,3352878,5406,NaN,100.0,65.0,17.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152364,3352878,5411,NaN,99.0,66.0,18.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152428,3352878,5416,NaN,NaN,67.0,22.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False
1152468,3352878,5421,NaN,NaN,68.0,22.0,NaN,NaN,NaN,NaN,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False

In [15]:
stop here

SyntaxError: invalid syntax (4067800170.py, line 1)

### Proceed from Merged Sheet

In [1]:
import pandas as pd
import numpy as np

In [2]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements = pd.read_csv("../data/Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements.csv")

In [3]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
0,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
1,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
2,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
3,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
4,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152908,3352878,5401,NaN,99.0,66.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,80.0,0.0
1152909,3352878,5406,NaN,100.0,65.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152910,3352878,5411,NaN,99.0,66.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152911,3352878,5416,NaN,NaN,67.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,90.0,0.0
1152912,3352878,5421,NaN,NaN,68.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.00,80.0,0.0

In [4]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements['patientunitstayid'] = Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements['patientunitstayid'].astype('category')
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
0,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
1,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
2,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
3,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
4,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152908,3352878,5401,NaN,99.0,66.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,80.0,0.0
1152909,3352878,5406,NaN,100.0,65.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152910,3352878,5411,NaN,99.0,66.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.00,90.0,0.0
1152911,3352878,5416,NaN,NaN,67.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,90.0,0.0
1152912,3352878,5421,NaN,NaN,68.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.00,80.0,0.0

In [5]:
Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152913 entries, 0 to 1152912
Data columns (total 16 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   patientunitstayid  1152913 non-null  category
 1   observationoffset  1152913 non-null  int64
 2   temperature        374731 non-null   float64
 3   sao2               1056425 non-null  float64
 4   heartrate          1149754 non-null  float64
 5   respiration        994367 non-null   float64
 6   cvp                543200 non-null   float64
 7   systemicsystolic   690767 non-null   float64
 8   systemicdiastolic  690764 non-null   float64
 9   systemicmean       694743 non-null   float64
 10  pasystolic         467193 non-null   float64
 11  padiastolic        467120 non-null   float64
 12  pamean             470308 non-null   float64
 13  st1                938151 non-null   float64
 14  st2                948085 non-null   float64
 15  st3                937375 non-null   float64
dtypes: category(1), float64(14), int64(1)
memory usage: 134.2 MB

In [6]:
Merged_1st48hrs_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements = Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements[Merged_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements['observationoffset'] <= (48 * 60)].reset_index(drop=True)  # First 48 hours of measurements    

df_train = Merged_1st48hrs_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements.reset_index(drop=True)
df_train

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
0,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
1,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
2,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
3,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
4,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487173,3352878,2856,38.8,98.0,93.0,19.0,15.0,121.0,67.0,86.0,47.0,20.0,31.0,50.00,120.0,70.0
487174,3352878,2861,38.7,98.0,95.0,22.0,15.0,123.0,68.0,87.0,48.0,20.0,31.0,50.00,110.0,50.0
487175,3352878,2866,38.7,97.0,94.0,20.0,15.0,124.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0
487176,3352878,2871,38.7,98.0,94.0,20.0,14.0,121.0,69.0,87.0,47.0,20.0,31.0,50.00,120.0,50.0
487177,3352878,2876,38.6,98.0,93.0,23.0,16.0,125.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0

In [7]:
df_train['patientunitstayid'] = df_train['patientunitstayid'].astype('category')

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487178 entries, 0 to 487177
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   patientunitstayid  487178 non-null  category
 1   observationoffset  487178 non-null  int64
 2   temperature        229772 non-null  float64
 3   sao2               463475 non-null  float64
 4   heartrate          485606 non-null  float64
 5   respiration        439176 non-null  float64
 6   cvp                306432 non-null  float64
 7   systemicsystolic   361597 non-null  float64
 8   systemicdiastolic  361597 non-null  float64
 9   systemicmean       363191 non-null  float64
 10  pasystolic         303019 non-null  float64
 11  padiastolic        302958 non-null  float64
 12  pamean             304619 non-null  float64
 13  st1                421878 non-null  float64
 14  st2                423614 non-null  float64
 15  st3                421686 non-null  float64
dtypes: category(1), float64(14), int64(1)
memory usage: 56.7 MB

In [9]:
df_train

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
0,143941,6,NaN,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
1,143941,11,NaN,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
2,143941,16,NaN,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
3,143941,21,NaN,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
4,143941,26,NaN,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487173,3352878,2856,38.8,98.0,93.0,19.0,15.0,121.0,67.0,86.0,47.0,20.0,31.0,50.00,120.0,70.0
487174,3352878,2861,38.7,98.0,95.0,22.0,15.0,123.0,68.0,87.0,48.0,20.0,31.0,50.00,110.0,50.0
487175,3352878,2866,38.7,97.0,94.0,20.0,15.0,124.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0
487176,3352878,2871,38.7,98.0,94.0,20.0,14.0,121.0,69.0,87.0,47.0,20.0,31.0,50.00,120.0,50.0
487177,3352878,2876,38.6,98.0,93.0,23.0,16.0,125.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0

In [10]:
# stop here, to check for percentage of missing values --> perc = ___

In [11]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Importing miceforest for multiple imputation. Use the option below or the option above
import miceforest as mf

In [12]:
df_train_amped = mf.ampute_data(df_train, perc=0.53, random_state=321)

In [13]:
kds = mf.ImputationKernel(
  df_train,
  save_all_iterations_data=True,
  random_state=321
)

# Run the MICE algorithm for __ iterations
kds.mice(10)

# Return the completed dataset.
df_imputed = kds.complete_data()

In [14]:
df_imputed

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,pasystolic,padiastolic,pamean,st1,st2,st3
0,143941,6,35.7,100.0,76.0,13.0,5.0,129.0,57.0,82.0,27.0,14.0,19.0,-0.10,0.2,0.2
1,143941,11,36.3,100.0,73.0,12.0,4.0,124.0,52.0,76.0,27.0,12.0,18.0,-0.15,0.1,0.3
2,143941,16,36.2,100.0,75.0,12.0,5.0,120.0,48.0,72.0,27.0,11.0,18.0,-0.40,0.3,0.8
3,143941,21,36.2,100.0,76.0,12.0,7.0,114.0,47.0,70.0,28.0,13.0,18.0,-0.50,0.7,1.1
4,143941,26,35.9,100.0,76.0,12.0,4.0,110.0,46.0,68.0,32.0,9.0,16.0,-0.50,0.7,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487173,3352878,2856,38.8,98.0,93.0,19.0,15.0,121.0,67.0,86.0,47.0,20.0,31.0,50.00,120.0,70.0
487174,3352878,2861,38.7,98.0,95.0,22.0,15.0,123.0,68.0,87.0,48.0,20.0,31.0,50.00,110.0,50.0
487175,3352878,2866,38.7,97.0,94.0,20.0,15.0,124.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0
487176,3352878,2871,38.7,98.0,94.0,20.0,14.0,121.0,69.0,87.0,47.0,20.0,31.0,50.00,120.0,50.0
487177,3352878,2876,38.6,98.0,93.0,23.0,16.0,125.0,69.0,88.0,47.0,20.0,31.0,50.00,110.0,50.0

In [15]:
df_imputed.to_csv("../data/df_imputed_1st48hrs_st123ICUstaysPeriodicVitals_WithAtLeast30ButLessThan33001Measurements_Ver4.csv", index=False)

In [16]:
df_imputed.columns.tolist()

['patientunitstayid',
 'observationoffset',
 'temperature',
 'sao2',
 'heartrate',
 'respiration',
 'cvp',
 'systemicsystolic',
 'systemicdiastolic',
 'systemicmean',
 'pasystolic',
 'padiastolic',
 'pamean',
 'st1',
 'st2',
 'st3']

In [17]:
import pandas as pd

In [18]:
Cleaned_ApacheResultsSheet = pd.read_csv('../data/EDA_SnapShot_Cleaned_ApacheResultsSheet.csv')

In [19]:
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet[Cleaned_ApacheResultsSheet['gender'].notnull()]
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['gender'] = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['gender'].map({'Male': 1, 'Female': 0, 'Unknown': -1})
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['oobintubday1'].notnull()]
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['activetx'].notnull()]
# Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['admitdiagnosis'].notnull()]
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['oobventday1'].notnull()]
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['motor-gcs'].notnull()]
Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['verbal-gcs'].notnull()]
# Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull['apachescore'].notnull()]

Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull

,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,predictedicumortality,actualicumortality,predictediculos,actualiculos,predictedhospitalmortality,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
0,141168,critical care medicine (CCM),Unknown,49.0,65.0,0.028889,True,3.091127,2.4972,0.059099,...,9.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
1,141194,critical care medicine (CCM),Unknown,57.0,70.0,0.046448,False,4.167129,3.3423,0.102283,...,4.0,1,NaN,False,4.0,6.0,3.0,NaN,NaN,False
2,141203,hospitalist,I,73.0,90.0,0.291609,False,8.670299,1.2979,0.470973,...,4.0,1,NaN,False,1.0,3.0,1.0,51.0,100.0,False
3,141208,hospitalist,I,17.0,17.0,0.001330,False,0.444563,0.5000,0.002249,...,7.0,1,NaN,False,5.0,6.0,3.0,NaN,NaN,False
4,141227,internal medicine,Unknown,83.0,100.0,0.335934,False,8.209624,1.1472,0.488562,...,6.0,1,NaN,False,4.0,6.0,3.0,65.0,21.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148527,3353235,cardiology,II,30.0,35.0,0.011009,False,1.934817,0.7423,0.022630,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148528,3353237,pulmonary/CCM,II,37.0,54.0,0.026984,False,2.566297,0.8812,0.062568,...,4.0,1,NaN,False,4.0,6.0,4.0,NaN,NaN,False
148529,3353251,cardiology,II,142.0,158.0,0.876797,False,8.920949,11.2909,0.918169,...,8.0,1,NaN,False,1.0,1.0,1.0,80.0,100.0,True
148530,3353254,hospitalist,II,18.0,35.0,0.011004,False,2.045046,0.2993,0.025801,...,4.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148531,3353263,nephrology,II,22.0,22.0,0.006508,False,1.754389,0.6444,0.012324,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False

In [20]:
CleanedApacheResults_Top6icuMortalityFactors = Cleaned_ApacheResultsSheet_Top6icuMortalityFactorsNotNull[['patientunitstayid', 'apachescore', 'gender', 'oobintubday1', 'activetx', 'oobventday1', 'motor-gcs', 'verbal-gcs']].drop_duplicates().reset_index(drop=True)
CleanedApacheResults_Top6icuMortalityFactors

,patientunitstayid,apachescore,gender,oobintubday1,activetx,oobventday1,motor-gcs,verbal-gcs
0,141168,65.0,1,False,True,False,6.0,5.0
1,141194,70.0,0,False,False,False,6.0,4.0
2,141203,90.0,1,False,True,True,3.0,1.0
3,141208,17.0,1,False,False,False,6.0,5.0
4,141227,100.0,0,False,True,True,6.0,4.0
...,...,...,...,...,...,...,...,...
146237,3353235,35.0,0,False,False,False,6.0,5.0
146238,3353237,54.0,1,False,False,False,6.0,4.0
146239,3353251,158.0,0,True,True,True,1.0,1.0
146240,3353254,35.0,0,False,True,False,6.0,5.0
146241,3353263,22.0,0,False,False,False,6.0,5.0

In [21]:
df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors = pd.merge(df_imputed, CleanedApacheResults_Top6icuMortalityFactors, on=['patientunitstayid'], how='inner').sort_values(by=['patientunitstayid', 'observationoffset']) #.drop(columns=['vitalperiodicid', 'etco2', 'icp']) 
df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors.to_csv("../data/df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors.csv", index=False)

In [22]:
df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors

,patientunitstayid,observationoffset,temperature,sao2,heartrate,respiration,cvp,systemicsystolic,systemicdiastolic,systemicmean,...,st1,st2,st3,apachescore,gender,oobintubday1,activetx,oobventday1,motor-gcs,verbal-gcs
0,143941,6,35.7,100.0,76.0,13.0,5.0,129.0,57.0,82.0,...,-0.10,0.2,0.2,66.0,0,True,True,True,6.0,5.0
1,143941,11,36.3,100.0,73.0,12.0,4.0,124.0,52.0,76.0,...,-0.15,0.1,0.3,66.0,0,True,True,True,6.0,5.0
2,143941,16,36.2,100.0,75.0,12.0,5.0,120.0,48.0,72.0,...,-0.40,0.3,0.8,66.0,0,True,True,True,6.0,5.0
3,143941,21,36.2,100.0,76.0,12.0,7.0,114.0,47.0,70.0,...,-0.50,0.7,1.1,66.0,0,True,True,True,6.0,5.0
4,143941,26,35.9,100.0,76.0,12.0,4.0,110.0,46.0,68.0,...,-0.50,0.7,1.2,66.0,0,True,True,True,6.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469388,3352878,2856,38.8,98.0,93.0,19.0,15.0,121.0,67.0,86.0,...,50.00,120.0,70.0,76.0,0,True,True,True,5.0,1.0
469389,3352878,2861,38.7,98.0,95.0,22.0,15.0,123.0,68.0,87.0,...,50.00,110.0,50.0,76.0,0,True,True,True,5.0,1.0
469390,3352878,2866,38.7,97.0,94.0,20.0,15.0,124.0,69.0,88.0,...,50.00,110.0,50.0,76.0,0,True,True,True,5.0,1.0
469391,3352878,2871,38.7,98.0,94.0,20.0,14.0,121.0,69.0,87.0,...,50.00,120.0,50.0,76.0,0,True,True,True,5.0,1.0
469392,3352878,2876,38.6,98.0,93.0,23.0,16.0,125.0,69.0,88.0,...,50.00,110.0,50.0,76.0,0,True,True,True,5.0,1.0

In [23]:
# stop here

### Construct Nested Data Frame by ICU Stay

In [24]:
import pandas as pd
import numpy as np
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

def create_nested_PatientUnitStay_DataRowframe(filename = '../data/df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors.csv'):
    """
    Creates a DataFrame where each row represents a patient and contains their
    complete time series as nested lists. This approach maintains the grouped
    structure while providing DataFrame functionality.
    
    Think of this like creating a patient registry where each patient has a
    complete medical chart attached to their record. The DataFrame gives us
    the patient-level structure, while the nested lists preserve the detailed
    time series data.
    
    Args:
        filename (str): Path to the ICU patient CSV file
        
    Returns:
        pandas.DataFrame: DataFrame with patients as rows and time series as nested lists
    """
    
    # First, let's read the original data to understand its structure
    print("Step 1: Reading and understanding the source data...")
    raw_df = pd.read_csv(filename)
    print(f"Original data shape: {raw_df.shape}")
    print(f"Columns: {list(raw_df.columns)}")
    
    # Ensure data is properly sorted by patient and time
    # This is crucial for maintaining chronological order within each patient's data
    raw_df = raw_df.sort_values(['patientunitstayid', 'observationoffset'])
    
    print(f"\nStep 2: Grouping patients and creating time series lists...")
    
    # Create a new DataFrame structure where each patient becomes one row
    PatientUnitStay_Summaries = []
    
    # Group by patient ID and process each patient's complete time series
    for PatientUnitStay_ID, PatientUnitStay_DataRow in raw_df.groupby('patientunitstayid'):
        
        # Convert the patient's time series data to lists
        # We'll create separate lists for each measurement type
        time_pt_inMinSinceICUadmission = PatientUnitStay_DataRow['observationoffset'].tolist()
        temperatures = PatientUnitStay_DataRow['temperature'].tolist()
        sao2_values = PatientUnitStay_DataRow['sao2'].tolist()
        heart_rates = PatientUnitStay_DataRow['heartrate'].tolist()
        respirations = PatientUnitStay_DataRow['respiration'].tolist()
        cvp_values = PatientUnitStay_DataRow['cvp'].tolist()
        sys_bp = PatientUnitStay_DataRow['systemicsystolic'].tolist()
        dia_bp = PatientUnitStay_DataRow['systemicdiastolic'].tolist()
        mean_bp = PatientUnitStay_DataRow['systemicmean'].tolist()
        pa_sys = PatientUnitStay_DataRow['pasystolic'].tolist()
        pa_dia = PatientUnitStay_DataRow['padiastolic'].tolist()
        pa_mean = PatientUnitStay_DataRow['pamean'].tolist()
        st1_values = PatientUnitStay_DataRow['st1'].tolist()
        st2_values = PatientUnitStay_DataRow['st2'].tolist()
        st3_values = PatientUnitStay_DataRow['st3'].tolist()
        gender_nested = PatientUnitStay_DataRow['gender'].tolist()
        oobintubday1_nested = PatientUnitStay_DataRow['oobintubday1'].tolist()
        activetx_nested = PatientUnitStay_DataRow['activetx'].tolist()
      #  admitdiagnosis_nested = PatientUnitStay_DataRow['admitdiagnosis'].tolist()
        oobventday1_nested = PatientUnitStay_DataRow['oobventday1'].tolist()
        motor_gcs_nested = PatientUnitStay_DataRow['motor-gcs'].tolist()
        verbal_gcs_nested = PatientUnitStay_DataRow['verbal-gcs'].tolist()
      #  apachescore_nested = PatientUnitStay_DataRow['apachescore'].tolist()

        # Calculate summary statistics for this patient
        # These help us understand the patient's overall condition and monitoring duration
        num_measurements = len(PatientUnitStay_DataRow)
        monitoring_duration_inMinutes = time_pt_inMinSinceICUadmission[-1] - time_pt_inMinSinceICUadmission[0] if len(time_pt_inMinSinceICUadmission) > 1 else 0
        avg_measurement_interval = monitoring_duration_inMinutes / (num_measurements - 1) if num_measurements > 1 else 0
        
        # Calculate clinical summary statistics
        avg_temperature = np.mean(temperatures)
        avg_heart_rate = np.mean(heart_rates)
        avg_sao2 = np.mean(sao2_values)
        avg_sys_bp = np.mean(sys_bp)
        avg_dia_bp = np.mean(dia_bp)
        temperature_range = max(temperatures) - min(temperatures)
        hr_variability = np.std(heart_rates)
        sao2_variability = np.std(sao2_values)

        # Create a comprehensive patient record
        patient_record = {
            'PatientUnitStay_ID': PatientUnitStay_ID,
            'num_measurements': num_measurements,
            'monitoring_start': time_pt_inMinSinceICUadmission[0],
            'monitoring_end': time_pt_inMinSinceICUadmission[-1],
            'monitoring_duration_inMinutes_minutes': monitoring_duration_inMinutes,
            'avg_measurement_interval': avg_measurement_interval,
            
            # Clinical summary statistics
            'avg_temperature': avg_temperature,
            'avg_heart_rate': avg_heart_rate,
            'avg_saO2': avg_sao2,
            'avg_systolic_bp': avg_sys_bp,
            'avg_diastolic_bp': avg_dia_bp,
            'temperature_range': temperature_range,
            'heart_rate_variability': hr_variability,
            'saO2_variability': sao2_variability,

            # Complete time series data as lists
            'time_series_offset': time_pt_inMinSinceICUadmission,
            'time_series_temperature': temperatures,
            'time_series_sao2': sao2_values,
            'time_series_heartrate': heart_rates,
            'time_series_respiration': respirations,
            'time_series_cvp': cvp_values,
            'time_series_systolic_bp': sys_bp,
            'time_series_diastolic_bp': dia_bp,
            'time_series_mean_bp': mean_bp,
            'time_series_pa_systolic': pa_sys,
            'time_series_pa_diastolic': pa_dia,
            'time_series_pa_mean': pa_mean,
            'time_series_st1': st1_values,
            'time_series_st2': st2_values,
            'time_series_st3': st3_values,
            'time_series_nested_gender': gender_nested,
            'time_series_oobintubday1_uponICUadmission': oobintubday1_nested,
            'time_series_activetx_uponICUadmission': activetx_nested,
           # 'time_series_admitdiagnosis': admitdiagnosis_nested,
            'time_series_oobventday1_uponICUadmission': oobventday1_nested,
            'time_series_motor_gcs_uponICUadmission': motor_gcs_nested,
            'time_series_verbal_gcs_uponICUadmission': verbal_gcs_nested #,
           # 'time_series_apachescore_uponICUadmission': apachescore_nested
        }
        
        PatientUnitStay_Summaries.append(patient_record)
    
    # Create the final DataFrame
    nested_df = pd.DataFrame(PatientUnitStay_Summaries)
    
    print(f"Step 3: Created nested DataFrame with shape: {nested_df.shape}")
    print(f"Each row represents one patient with their complete time series")
    
    return nested_df

In [25]:
Nested_df_imputed_1st48hrs_st123ICUstaysPeriodicVitals = pd.DataFrame(create_nested_PatientUnitStay_DataRowframe(filename = '../data/df_imputedVitalsSt123_ApacheIVaTop6MortalityFactors.csv'))

Step 1: Reading and understanding the source data...
Original data shape: (469393, 23)
Columns: ['patientunitstayid', 'observationoffset', 'temperature', 'sao2', 'heartrate', 'respiration', 'cvp', 'systemicsystolic', 'systemicdiastolic', 'systemicmean', 'pasystolic', 'padiastolic', 'pamean', 'st1', 'st2', 'st3', 'apachescore', 'gender', 'oobintubday1', 'activetx', 'oobventday1', 'motor-gcs', 'verbal-gcs']

Step 2: Grouping patients and creating time series lists...
Step 3: Created nested DataFrame with shape: (976, 35)
Each row represents one patient with their complete time series

In [26]:
Nested_df_imputed_1st48hrs_st123ICUstaysPeriodicVitals

,PatientUnitStay_ID,num_measurements,monitoring_start,monitoring_end,monitoring_duration_inMinutes_minutes,avg_measurement_interval,avg_temperature,avg_heart_rate,avg_saO2,avg_systolic_bp,...,time_series_pa_mean,time_series_st1,time_series_st2,time_series_st3,time_series_nested_gender,time_series_oobintubday1_uponICUadmission,time_series_activetx_uponICUadmission,time_series_oobventday1_uponICUadmission,time_series_motor_gcs_uponICUadmission,time_series_verbal_gcs_uponICUadmission
0,143941,575,6,2876,2870,5.000000,37.043043,76.794783,98.300870,101.259130,...,"[19.0, 18.0, 18.0, 18.0, 16.0, 14.0, 13.0, 13....","[-0.1, -0.15000001, -0.40000001, -0.5, -0.5, -...","[0.2, 0.1, 0.30000001, 0.69999999, 0.69999999,...","[0.2, 0.30000001, 0.80000001, 1.1, 1.2, 1.4, 1...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
1,161093,573,4,2879,2875,5.026224,37.115620,74.157068,97.200698,113.804538,...,"[21.0, 35.0, 33.0, 16.0, 28.0, 29.0, 32.0, 21....","[0.0, -0.2, -0.2, -0.2, -0.2, -0.1, -0.1, -0.2...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.1, 0.0,...","[0.1, 0.2, 0.1, 0.2, 0.1, 0.1, 0.0, 0.1, 0.2, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
2,166995,524,21,2876,2855,5.458891,37.795229,118.765267,94.557252,101.164122,...,"[20.0, 35.0, 33.0, 30.0, 23.0, 33.0, 20.0, 32....","[0.2, 0.2, 0.30000001, 0.2, 0.30000001, 0.2, 0...","[0.34999999, 0.40000001, 0.40000001, 0.4000000...","[0.050000001, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
3,177460,576,5,2880,2875,5.000000,37.157639,84.744792,96.095486,112.310764,...,"[28.0, 17.0, 16.0, 21.0, 28.0, 16.0, 18.0, 25....","[0.0, 0.30000001, 0.30000001, 0.0, -0.1, 0.0, ...","[-0.2, 0.0, -0.1, -0.1, -0.5, -0.5, -0.6999999...","[-0.2, -0.1, 0.0, -0.1, -0.40000001, -0.400000...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
4,191266,570,10,2880,2870,5.043937,35.843333,109.840351,95.077193,100.335088,...,"[11.0, 10.0, 11.0, 12.0, 12.0, 15.0, 13.0, 16....","[-0.1, -0.1, -0.1, -0.1, -0.1, 0.0, -0.1, 0.0,...","[-0.5, -0.30000001, -0.30000001, -0.30000001, ...","[-0.30000001, -0.2, -0.30000001, -0.2, -0.3000...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,3352114,286,21,1446,1425,5.000000,37.250350,87.472028,98.328671,115.262238,...,"[17.0, 18.0, 18.0, 19.0, 18.0, 18.0, 19.0, 19....","[0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[130.0, 120.0, 110.0, 100.0, 90.0, 90.0, 80.0,...","[140.0, 120.0, 120.0, 110.0, 110.0, 100.0, 90....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
972,3352178,301,15,1515,1500,5.000000,36.519269,82.428571,97.332226,118.073090,...,"[23.0, 25.0, 23.0, 21.0, 20.0, 21.0, 20.0, 20....","[0.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0...","[50.0, 50.0, 60.0, 50.0, 60.0, 60.0, 50.0, 60....","[45.0, 50.0, 50.0, 40.0, 40.0, 40.0, 40.0, 40....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
973,3352344,348,5,1740,1735,5.000000,37.364799,104.497126,98.537356,114.752874,...,"[17.0, 26.0, 26.0, 26.0, 31.0, 28.0, 21.0, 20....","[20.0, 20.0, 20.0, 20.0, 30.0, 30.0, 20.0, 20....","[30.0, 40.0, 30.0, 40.0, 30.0, 40.0, 40.0, 40....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 10.0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
974,3352620,429,26,2876,2850,6.658879,37.226107,90.668998,97.431235,160.184149,...,"[40.0, 18.0, 25.0, 33.0, 22.0, 19.0, 22.0, 25....","[0.0, 0.1, 0.1, 0.1, 0.0, 0.1, 0.0, 0.0, -1.5,...","[0.60000002, 0.60000002, 0.5, 0.60000002, 0.5,...","[0.5, 0.40000001, 0.40000001, 0.40000001, 0.5,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[False, False, False, False, False, False, Fal...","[True, True, True, True, True, True, True, Tru...","[False, False, False, False, False, False, Fal...","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, ...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ..."
975,3352878,571,26,2876,2850,5.000000,38.251313,90.126095,98.924694,106.835377,...,"[36.0, 38.0, 36.0, 36.0, 35.0, 34.0, 33.0, 31....","[30.0, 10.0, 0.0, 20.0, 30.0, 10.0, 0.0, 20.0,...","[60.0, 80.0, 70.0, 100.0, 80.0, 80.0, 40.0, 70...","[50.0, 60.0, 40.0, 70.0, 50.0, 20.0, 50.0, 40....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[True, True, True, True, True, True, True, Tru...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."

In [27]:
Cleaned_ApacheResultsSheet = pd.read_csv('../data/EDA_SnapShot_Cleaned_ApacheResultsSheet.csv')
Cleaned_ApacheResultsSheet

,patientunitstayid,physicianspeciality,physicianinterventioncategory,acutephysiologyscore,apachescore,predictedicumortality,actualicumortality,predictediculos,actualiculos,predictedhospitalmortality,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
0,141168,critical care medicine (CCM),Unknown,49.0,65.0,0.028889,True,3.091127,2.4972,0.059099,...,9.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
1,141194,critical care medicine (CCM),Unknown,57.0,70.0,0.046448,False,4.167129,3.3423,0.102283,...,4.0,1,NaN,False,4.0,6.0,3.0,NaN,NaN,False
2,141203,hospitalist,I,73.0,90.0,0.291609,False,8.670299,1.2979,0.470973,...,4.0,1,NaN,False,1.0,3.0,1.0,51.0,100.0,False
3,141208,hospitalist,I,17.0,17.0,0.001330,False,0.444563,0.5000,0.002249,...,7.0,1,NaN,False,5.0,6.0,3.0,NaN,NaN,False
4,141227,internal medicine,Unknown,83.0,100.0,0.335934,False,8.209624,1.1472,0.488562,...,6.0,1,NaN,False,4.0,6.0,3.0,65.0,21.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148527,3353235,cardiology,II,30.0,35.0,0.011009,False,1.934817,0.7423,0.022630,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148528,3353237,pulmonary/CCM,II,37.0,54.0,0.026984,False,2.566297,0.8812,0.062568,...,4.0,1,NaN,False,4.0,6.0,4.0,NaN,NaN,False
148529,3353251,cardiology,II,142.0,158.0,0.876797,False,8.920949,11.2909,0.918169,...,8.0,1,NaN,False,1.0,1.0,1.0,80.0,100.0,True
148530,3353254,hospitalist,II,18.0,35.0,0.011004,False,2.045046,0.2993,0.025801,...,4.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
148531,3353263,nephrology,II,22.0,22.0,0.006508,False,1.754389,0.6444,0.012324,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False

In [28]:
df_imputed_MergedWith_Cleaned_ApacheResultsSheet = pd.merge(Nested_df_imputed_1st48hrs_st123ICUstaysPeriodicVitals, Cleaned_ApacheResultsSheet, left_on=['PatientUnitStay_ID'], right_on = ['patientunitstayid'], how='inner').sort_values(by=['patientunitstayid']).reset_index(drop=True) 
df_imputed_MergedWith_Cleaned_ApacheResultsSheet

,PatientUnitStay_ID,num_measurements,monitoring_start,monitoring_end,monitoring_duration_inMinutes_minutes,avg_measurement_interval,avg_temperature,avg_heart_rate,avg_saO2,avg_systolic_bp,...,dischargelocation,visitnumber,amilocation,day1meds,day1verbal-gcs,day1motor-gcs,day1eyes-gcs,day1pao2,day1fio2,PredictedICUmortality_binary
0,143941,575,6,2876,2870,5.000000,37.043043,76.794783,98.300870,101.259130,...,4.0,1,NaN,False,5.0,6.0,4.0,186.0,50.0,False
1,161093,573,4,2879,2875,5.026224,37.115620,74.157068,97.200698,113.804538,...,4.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
2,166995,524,21,2876,2855,5.458891,37.795229,118.765267,94.557252,101.164122,...,4.0,1,NaN,False,5.0,6.0,4.0,113.0,100.0,False
3,177460,576,5,2880,2875,5.000000,37.157639,84.744792,96.095486,112.310764,...,8.0,2,6.0,False,5.0,6.0,4.0,NaN,NaN,False
4,191266,570,10,2880,2870,5.043937,35.843333,109.840351,95.077193,100.335088,...,9.0,1,NaN,False,1.0,1.0,1.0,77.0,60.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,3352114,286,21,1446,1425,5.000000,37.250350,87.472028,98.328671,115.262238,...,8.0,1,NaN,False,5.0,6.0,4.0,NaN,NaN,False
972,3352178,301,15,1515,1500,5.000000,36.519269,82.428571,97.332226,118.073090,...,8.0,1,NaN,False,5.0,6.0,4.0,158.0,100.0,False
973,3352344,348,5,1740,1735,5.000000,37.364799,104.497126,98.537356,114.752874,...,8.0,1,NaN,False,5.0,6.0,4.0,318.0,100.0,False
974,3352620,429,26,2876,2850,6.658879,37.226107,90.668998,97.431235,160.184149,...,8.0,1,NaN,False,5.0,6.0,4.0,95.0,21.0,False
975,3352878,571,26,2876,2850,5.000000,38.251313,90.126095,98.924694,106.835377,...,8.0,1,NaN,False,1.0,5.0,1.0,95.0,100.0,False

In [29]:
df_imputed_MergedWith_Cleaned_ApacheResultsSheet.to_csv("../data/First48Hrs_NestedDF_afterMICEforest_MergedWith_Cleaned_ApacheResultsSheet_Ver4.csv", index=False)

In [30]:
time_series_columns = [column for column in df_imputed_MergedWith_Cleaned_ApacheResultsSheet.columns if column.startswith('time_series_')]  
time_series_columns  # use these header names for LSTM processing in the next step

['time_series_offset',
 'time_series_temperature',
 'time_series_sao2',
 'time_series_heartrate',
 'time_series_respiration',
 'time_series_cvp',
 'time_series_systolic_bp',
 'time_series_diastolic_bp',
 'time_series_mean_bp',
 'time_series_pa_systolic',
 'time_series_pa_diastolic',
 'time_series_pa_mean',
 'time_series_st1',
 'time_series_st2',
 'time_series_st3',
 'time_series_nested_gender',
 'time_series_oobintubday1_uponICUadmission',
 'time_series_activetx_uponICUadmission',
 'time_series_oobventday1_uponICUadmission',
 'time_series_motor_gcs_uponICUadmission',
 'time_series_verbal_gcs_uponICUadmission']